%% introduction to MATLAB notes

% Matthew Tarnowski
% 13th November 2017
% synthetic biology 
% DTC MATLAB module
% day 1 of MATLAB module
% read on for notes and exercises

%% playing around - this is my first matlab file ever!
% Q what is the difference between saving and publishing?
% A seems to be that publishing spits out a box of what the code in
% the file does whereas saving just saves the data in the file

%BODMAS - 
%brackets
%, orders (root/power), 
%division, 
%multiplication,
%addition, 
%subtraction

%function test

%disp("hello")

%end


%% notes from introductory lecture

% %% this is how you add titles (with %%)

% this is how you add notes/comments (with %)

%this is how you add variable names:
%_name_

%add latex equations using:
% $$ y = x $$


% for more info on the publish operation: 
% https://uk.mathworks.com/help/matlab/ref/publish.html


%latex (x^2 + 1/4)


%% working through: an introduction to MATLAB worksheet sections 1-3
%date - 20171114; day 1 of course

% type an equation which doesn't end in a colon to make it output to the
% screen:
x=3+4*(1+6/3)

x

%or type a colon after the equation to ensure it doesn't get published:
x=3+4*(1+6/3)

%then you can print x to screen by simply typing the variable:

x


%% Section 4 - vectors (AKA arrays) and matrices

% example: vector u = (1,4,9) may be entered in to matlab by the following
% methods:
% inputting all the elements simultaneously - this prints the vector
u = [1 4 9]

% mat lab is zero-indexed! :(
%but you can enter the elements of the vector one by one
v(1) = 4;
v(2) = 5;
v(3) = 6;
v

% the transpose of u may be written as u'
u'

%vectors with columns can be written by putting semicolons between the
%vector elements:
v=[4; 5; 6]

% inside the square brackets, the semicolon denotes a new line

% matrices

% *matrices*
A(1,1)=1;
A(1,2)=2;
A(2,1)=3;
A(2,2)=4

%hmm maybe 1-indexing isn't so bad.. 
% A(i,j) corresponds to the element in the ith row and the jth column of
% the matrix A

% you can also type the same size matrix by entering elements in the same
% row with just spaces between them and then entering new lines using ;

B = [3 2; 7 6]

% 
% *4.2 - changing individual elements of a matrix Can be done by specifying*
% *the individual element* :

B(1,2) = 100

%An alternative way is to double click on “A” in the
%Workspace window. This opens a window containing
%the contents of the matrix A.

%  *looking at parts of matrices*
C=[1 2 3 4; 5 6 7 8; 9 10 11 12];

% to view a certain column n type C(:,n) & do similar for a given row
% to view certain rows or columns specify a range m:n

%% Addition, subtraction and multiplication of vectors and matrices

% _the matrices must be of the same size to be a/s/m_
% as advised in the maths module, the number of columns of the first 
% matrix in the multiplication must equal the number of rows in the second
% matrix to be multiplied
% IE matrix A of dimensions 3 x 4 and matrix B dimensions 4 x 23 can be multiplied
% _ (3 x 4) X (4 x 23) -> (3 x 23) product matrix dimensions

%% 6 - generating vectors using ":"

M = 1:10

% A vector y consisting of 100 points equally
%spaced between 5 and 15 may be generated by
%typing:
y=linspace(5,15,100);

%% 7 - some special matrices and vectors

% zeros(m,n) creates a matrix of dimensions m,n
zeros(3,2)

% ones(m,n) does same thing but generates a matrix of ones

% eye(m,n) creates diagonal entries equal to
%1 and all other entries equal to 0 

eye(4,6)
%% questions

% - how to insert equations in the latex format
